language: bash

stages:
  - test
  - deploy

os:
- linux

env:
  - BASHVER= SHELLCHECK=true
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4
  - BASHVER=5

matrix:
  include:
    - os: osx
      env: ''
    - stage: deploy  
      env: ''
      before_script:
      - sudo apt-get install python3-pip
      - sudo pip3 install sphinx-multiversion sphinxcontrib-programoutput recommonmark
      script:
      - | 
        mkdir html
        sphinx-multiversion docs/source html
      before_deploy:
        - touch html/.nojekyll
      deploy:
      - provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: false
        local_dir: html

services:
  - docker

before_script:
 - |
   if [[ "${TRAVIS_OS_NAME:-}" == 'linux' && "$SHELLCHECK" == 'true' ]]; then
     sudo apt-get install shellcheck
   fi

script:
- |
  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' && "$SHELLCHECK" == 'true' ]]; then
    ./shellcheck.sh
    exit $?
  fi

  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' && -n "${BASHVER}" ]]; then
    docker build --build-arg bashver="${BASHVER}" --tag "bats/bats:bash-${BASHVER}" . || exit $?
    docker run -it "bash:${BASHVER}" --version || exit $?
    time docker run -it "bats/bats:bash-${BASHVER}" --tap /opt/bats/test || exit $?
    # also test running (recursively!) in parallel
    time docker run -it -e BATS_NUMBER_OF_PARALLEL_JOBS=2 "bats/bats:bash-${BASHVER}" --tap /opt/bats/test || exit $?
  else
    time bin/bats --formatter tap test
    # allow for some parallelity without GNU parallel, e.g. on MacOS
    time BATS_NO_PARALLELIZE_ACROSS_FILES=1 BATS_NUMBER_OF_PARALLEL_JOBS=2 bin/bats --tap test
  fi
      

notifications:
  email:
    on_success: never
